run:
	cd frontend && npm install && npm start
	cd backend && python -m venv venv && source venv/bin/activate && pip install -r requirements.txt && pip install --upgrade pip && uvicorn app.main:app --reload
